import React from "react";

const About = () => {
  return (
    <div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      this is About
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
      <div>p</div>
    </div>
  );
};

export default About;
